---
title: "Modeling public opinion over time and space: Trust in state institutions in Europe, 1989-2019"
author: "Marta Kołczyńska"
date: 2024-04-20T10:58:11
topic: ["political trust"]
tags: ["public opinion", "political trust", "survey data", "latent trend models", "splines", "irt"]
output: 
  blogdown::html_page:
    toc: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

A new paper titled "Modeling Public Opinion Over Time and Space: Trust in State Institutions in Europe, 1989-2019", co-authored by Marta Kołczyńska, Paul-Christian Bürkner, Lauren Kennedy, and Aki Vehtari, was published in [**Survey Research Methods**](https://ojs.ub.uni-konstanz.de/srm/index){target="_blank"}. 

The paper estimates trends in political trust in Europe in 1989-2019 based on data from 1.7 million respondents from 13 cross-national surveys, and examines levels in political trust both overall, and by age, gender, and education. 

Methodologically, we develop a framework for the estimation of trends in mass public opinion consisting of three components: (1) the response model, (2) the latent trend model, and (3) representativeness adjustments. In our analysis we choose the following methods for the components, respectively: item response theory models, splines, and post-stratification. We discuss the assumptions behind our approach and compare it to alternative approaches proposed in the literature on macro-level public opinion.


From the abstract:
  
  > *Combining public opinion data from different sources enables new cross-national and longitudinal research, but is accompanied by unique challenges. The analytic strategy we propose relies on Bayesian explanatory item response theory models to address differences in the measurement of attitudes, and poststratification that uses administrative population data to improve the quality of estimates and correct for differences in sample representativeness. Partially pooled models with data from all countries would be prohibitively slow, so we estimate separate by-country models in a way that maintains comparability of estimates across countries. We apply this strategy to data from 13 cross-national research projects from 27 European countries to estimate trajectories of political trust between 1989-2019.*
  
Replication materials (data and code) are available in this Open Science Framework [**repository**](https://osf.io/uyzfe/){target="_blank"}.

The full paper is available [**here**](https://ojs.ub.uni-konstanz.de/srm/article/view/8119){target="_blank"}.

Different ways of estimating latent trends are examined in another paper, by Marta Kołczyńska and Paul-Christian Bürkner, titled [**"Modeling public opinion over time: A simulation study of latent trend models"**](https://polarization-political-trust.netlify.app/post/simulation-latent-trend-models/).
